### ISSUE TITLE
Request for incubation: conda-store

### ISSUE THREAD

**Issue by jaimergp** [conda-incubator/governance#106]
Hey team, the conda-store team would like to move their projects to `conda-incubator`.

This means transferring:

- https://github.com/Quansight/conda-store
- https://github.com/Quansight/conda-store-ui
- https://github.com/Quansight/jupyterlab-conda-store

And creating a `conda-incubator/conda-store` team with the following external collaborators:

- @dharhas
- @pierrotsmnrd
- @costrouc
- @aktech
- @anirrudh
- @trallard
- @pavithraes
- @iameskild

I am submitting this issue for the historical record, but any feedback is welcome and appreciated!

**Comment by jezdez** [comment]
So stoked for you all doing this!

**Comment by jaimergp** [comment]
Done! https://github.com/orgs/conda-incubator/repositories?q=conda-store&type=all&language=&sort=

cc @conda-incubator/conda-store

**Comment by jezdez** [comment]
Huzzah!
