### ISSUE TITLE
Request for incubation: `conda-tui`

### ISSUE THREAD

**Issue by mattkram** [conda-incubator/governance#108]
Hi team, the conda-tui team would like to move our project to conda-incubator.

I would like to migrate the repository at: https://github.com/anaconda-hackdays/conda-tui

And create a conda-incubator/conda-tui team with the following collaborator: @mattkram

I am submitting this issue for the historical record. Any feedback is welcome and appreciated!

**Comment by mattkram** [comment]
CC: @chenghlee

**Comment by chenghlee** [comment]
I've not heard any objections from other members of the Steering Council, so I'll go ahead and [sponsor incubation](https://github.com/conda-incubator/governance#incubation) of this project.

**Comment by chenghlee** [comment]
I've not heard any objections from other members of the Steering Council, so I'll go ahead and [sponsor incubation](https://github.com/conda-incubator/governance#incubation) of this project.
