### ISSUE TITLE
Request for incubation: `conda-recipe-manager`

### ISSUE THREAD

**Issue by schuylermartin45** [conda-incubator/governance#128]
Hello everyone, I would like to move the [conda-recipe-manager](https://github.com/anaconda/conda-recipe-manager) project to `conda-incubator`.

We hope that this move will allow others to easily contribute to our recipe automation efforts. To start, our primary focus is on the conversion of our existing recipe format to the new "v1" format proposed in [CEP-13](https://github.com/conda-incubator/ceps/blob/main/cep-13.md) & [CEP-14](https://github.com/conda-incubator/ceps/blob/main/cep-14.md)

I am currently working through migrating this work from another Anaconda project, [percy](https://github.com/anaconda-distribution/percy). As of writing this proposal, the conversion is not complete BUT most of the applicable code and configuration files have been copied-over.

I would like to migrate the repository at: https://github.com/anaconda/conda-recipe-manager
I would like the existing build-team to manage this project.

I am submitting this issue for the historical record. Any feedback is welcome and appreciated! Thanks!

(The text of this issue was heavily based on the precedent set by Issue https://github.com/conda-incubator/governance/issues/108)

**Comment by schuylermartin45** [comment]
@chenghlee and @jezdez for visibility ^

**Comment by jezdez** [comment]
I'm happy to sponsor this and will set up the team, and I'll need to do the repo transfer since GitHub only allows org owners to migrate whole repos

**Comment by jezdez** [comment]
https://matrix.to/#/!zjZSkaZgcvxBwdCKne:matrix.org/$2_FaMoMRCcZ5_rnmDtdahjWrc4wpx34dhjQpI4ML52o?via=matrix.org&via=mozilla.org

**Comment by beckermr** [comment]
How does this relate to souschef from @marcelotrevisani?

**Comment by beckermr** [comment]
Not blocking incubation, just wondering.

**Comment by wolfv** [comment]
Very excited about the potential recipe translation enabled by this 👍

**Comment by schuylermartin45** [comment]
@beckermr I don't want to speak for @marcelotrevisani but I _believe_ Marcel and I briefly spoke over a community call about a month back, where I presented a [slide deck on the project](https://github.com/anaconda/conda-recipe-manager/blob/main/docs/presentations/Anaconda%20Recipe%20Parser%20-%20Introduction.pdf). As far as I understand it/have been able to find in the community, this new parser is the most advanced recipe editing tool currently available.

Of course I'm biased as the author, but I don't think most of the existing efforts convert the recipe into a parse-tree and/or have the ability to manipulate JINJA and selector syntax. I built this originally for Anaconda's needs but my team and I noticed an opportunity to use this to speed up the adoption of the v1/rattler-build format and took it.

I also believe on the call that we all expect that multiple tools may be required to update all 20,000+ conda-forge recipes and 2,600+ Anaconda recipes. So I wouldn't take this as a complete replacement for souschef, as much as another tool in our toolbox.

Let me know if you have any additional questions!

**Comment by beckermr** [comment]
Ahhh cool. You should checkout what I wrote for the conda-forge bot:

 - https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/recipe_parser/_parser.py
 - https://github.com/regro/cf-scripts/blob/master/tests/test_recipe_parser.py

and its tests.

**Comment by schuylermartin45** [comment]
@jezdez @chenghlee I haven't seen any opposition, do we feel confident about moving this project into the incubator?

**Comment by jezdez** [comment]
@schuylermartin45 Indeed, I'll recreate the build tools team in the conda-incubator (since it currently only exists in the conda org) and then start the transition of the repo.

**Comment by jezdez** [comment]
@conda-incubator/builds-tools Hey all, heads-up that I've just created the "build tools" here in the **conda-incubator** organization as well.

The team in the **conda** organization had been created following the discussion in https://github.com/conda/conda-build/issues/4698.

The reason to add the team here as well is so we can add the new conda-recipe-manager project to the incubator under that guidance of the "build tools" team.

**Comment by jezdez** [comment]
And transferred! https://github.com/conda-incubator/conda-recipe-manager
