### ISSUE TITLE
Ask who wants to become emeritus-core

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/governance#31]
Following the [terms defined under "Teams & Roles"](https://github.com/conda-incubator/governance/tree/e34eb0ae4a1e6873531e9c94147a0a5db02a8278#teams--roles), I was wondering if it's time to ask the core team if anyone wants to become emeritus-core (e.g. since some have moved on)?

> Core members that are inactive (commits, GitHub comments/issues/reviews, dev meetings, and voting on polls) in the past six months will be asked if they want to become emeritus-core developers. One week after asking, if the inactive core member has not responded, they will be automatically moved to emeritus status. 

Full disclosure: I'm not a core member (read: applied and voted in by the core membership) and can't do this myself.

**Comment by beckermr** [comment]
Thanks @jezdez! This was on my todo list but has not gotten to the top yet.

**Comment by beckermr** [comment]
I sent this note out today.

**Comment by jezdez** [comment]
Thank you @beckermr!
