### ISSUE TITLE
governance update

### ISSUE THREAD

**Issue by beckermr** [conda-incubator/governance#35]
Following changes at anaconda inc and the creation of conda/ceps and https://github.com/conda-archive, it seems to be time for us to revisit the governance, proposing an update and voting on it. 

I am starting this issue to gather comments/feedback.

cc @jezdez

**Comment by beckermr** [comment]
Some thoughts/comments:

1. Our current governance might be a bit too complicated.
2. The distinction between enhancement proposal votes and standards repo votes is not clear. We might just want the former.
3. If we can use conda-archive, then the attic stuff can go.

**Comment by beckermr** [comment]
Also there are some simpler ideas here that might be of use: https://github.blog/2021-07-22-minimum-viable-governance-lightweight-community-structure-foss-projects/

**Comment by jezdez** [comment]
> Some thoughts/comments:
> 
> 1. Our current governance might be a bit too complicated.
> 2. The distinction between enhancement proposal votes and standards repo votes is not clear. We might just want the former.
> 3. If we can use conda-archive, then the attic stuff can go.

FTR, I chose to not use "attic" for the org name to not conflict with the current governance policy and require an explicit update of the policy to cater to it. conda-archive is an intermediate step to get old repos out of the way in the conda org while I'm working on doing the permission review and revamp. All repos in there were archived or abandoned already.

I would suggest to add the conda-archive to the list of orgs where the conda organization is maintained and later explain the full life-cycle of conda-related projects, basically conda-archive being the long-term storage for unmaintained/abandoned etc projects. Of course the org could also be renamed to conda-attic if requested by the current signatories.

**Comment by beckermr** [comment]
This all sounds great @jezdez! I don't think there are strong opinions on what to call what here or the like. I think my own interest is in making things clear and simple for everyone. Renaming to conda-archive with a separate org is great by me!

BTW, there are a few projects (maybe only one) in conda-archive that were (soft-)forked to conda-incubator (e.g. libronda). We should make sure those have one home when the time comes.

**Comment by jezdez** [comment]
> This all sounds great @jezdez! I don't think there are strong opinions on what to call what here or the like. I think my own interest is in making things clear and simple for everyone. Renaming to conda-archive with a separate org is great by me!

Same!

> BTW, there are a few projects (maybe only one) in conda-archive that were (soft-)forked to conda-incubator (e.g. libronda). We should make sure those have one home when the time comes.

Good catch, didn't know that.
