### ISSUE TITLE
Finalizing Governance

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/governance#43]
Hi All,

You may have noticed recent activity in the [conda-governance incubator project](https://github.com/conda-incubator/governance).  So far changes have been limited to typos/formatting (PR #40), and clarity updates (Issue #41)—updates that don’t change policy in any way.

However, that is about to change.  I really, really want to get our governance out of incubator status and into actual use.  In the next 2-3 months look for these three efforts:

### 1. Code of Conduct 

We need to have a working, welcoming, and enforceable code of conduct and we need it soon.  Not having this sends absolutely the wrong message to both current and potential community members.

Our current [draft code of conduct](https://github.com/conda-incubator/governance/blob/master/CODE_OF_CONDUCT.md) is a copy of the [NumFOCUS CoC template](https://github.com/numfocus/numfocus/blob/master/manual/numfocus-coc.md).  It’s a great place to start, but I suspect we could improve it some before we adopt it.  We are also going to need a CoC committee to respond to reports. 

**Expect an issue in a week or two about the CoC.**  If you care about CoCs then please join that discussion (and maybe the committee too).  Several of you expressed an interest on the most recent conda community call.  Expect a shout when this issue is created.

### 2. Fiscal Sponsorship

The [conda Organization](https://github.com/conda-incubator/governance/blob/master/README.md#naming--manifest) has historically been funded by Anaconda, Inc. and is currently not *Fiscally Sponsored* by a non-profit. conda is a NumFOCUS *Affiliated* Project, but that doesn’t allow the conda Organization to handle trademarks, and we can’t deal with outside funding in any way (receiving or distributing).

**Expect an issue (maybe in May?) about applying for fiscal sponsorship, probably with NumFOCUS.** Their next application review period is in July.  If you have experience with fiscal sponsorship or with NumFOCUS then please consider joining this discussion.

### 3. Propose a Novel Voting and Membership Structure for conda Governance

A widespread and continuing issue in open source is how to encourage contributions (including input on project direction) from commercial entities, while avoiding having companies’ financial interests override what is best for the overall community. 

**Look for an issue proposing a Steering Council model that *considers the source of Council members’ financial backing when weighting the Council votes of individual members.***  Whenever more than one Council member has common funding the weight of their votes will be reduced compared to Council members that do not share common funding sources with other Council members.  We hope to propose a weighting that makes it impossible for any one company (or grant consortium) to unilaterally enforce its will on the conda Organization.

Of course the devil is in the details.  We hope to publish a draft proposal by the end of April.  We are pretty sure there will be plenty of discussion on this one.

Thanks for reading this far. Please let me know if you have questions, and please keep your eyes open for governance issues in the next few months.

Cheers,
Dave C

**Comment by tnabtaf** [comment]
An update on the **Code of conduct:**

Issue #46 proposes a sub-team for finalizing our current Code of Conduct, and for nominating the first Code of Conduct committee.

**Comment by tnabtaf** [comment]
Issue #47 addresses item # 3 above: Propose a Novel Voting and Membership Structure for conda Governance

**Comment by tnabtaf** [comment]
There are now open issues / pull requests for each of the 3 major pushes in this issue.

**Comment by beckermr** [comment]
I am closing this one. We should open more issues for the points @mbargull collated.
