### ISSUE TITLE
Fiscal Sponsorship Proposal

### ISSUE THREAD

**Issue by tnabtaf** [conda-incubator/governance#54]
Hi All,

The last of the three major goals in the Finalizing Governance issue (#43) is **Fiscal Sponsorship**:

> The [conda Organization](https://github.com/conda-incubator/governance/blob/master/README.md#naming--manifest) has historically been funded by Anaconda, Inc. and is currently not *Fiscally Sponsored* by a non-profit. conda is a NumFOCUS *Affiliated Project*, but that doesn’t allow the conda Organization to handle trademarks, and we can’t deal with outside funding in any way (receiving or distributing).

Applications are due by July 15.  With that in mind, I have walked through the [NumFOCUS application form](https://numfocus.typeform.com/to/VUPE35?typeform-source=numfocus.org) and created draft responses to each question (see below).

Note that this application has been given a lot less thought and by a lot less people, than have the Code and Conduct and Governance proposals.  Most of these items will be only included in the application, but some of them will end up on the Conda project web page at NumFOCUS.  Please review this proposal in the next few weeks.  Improvement to anything, but especially text that will eventually show up on the NumFOCUS website, are strongly encouraged.

----

## 1. Does your project have a contributor Code of Conduct? (Yes/No)

Yes

## 2. What is the name of your project?

conda (or is it is Conda? See [this conda-docs issues](https://github.com/conda/conda-docs/issues/803)).

## 3. Please provide the url of your project's (primary) repo:

https://github.com/conda

## 4. Your project's website:

We currently are focused around our two GitHub organizations:
1. https://github.com/conda
2. https://github.com/conda-incubator

We are planning to turn conda.org into a project community website later this year.

## 5. Please provide a summary description of your project in a few sentences:

Conda is an open source package management system and environment management system that runs on Windows, macOS, Linux and z/OS. Conda quickly installs, runs and updates packages and their dependencies. Conda easily creates, saves, loads and switches between environments on your local computer. Conda supports software written in any language.

## 6. Does your project have a logo?

Yes

## 7. Please upload a .svg file of your project's logo.  A "square" format is best.

Will use the conda C logo

## 8. Your project's Twitter handle or other social media handles/urls
Twitter: @condaproject

## 9. Why do you want your project to join NumFOCUS?

The Conda Organization currently has no legal status.  We cannot accept funding or formally sponsor work or events, and we can't manage trademarks.  Joining NumFOCUS enables us to do all those things, and would also raise Conda's visibility in the open source scientific software community.

## 10. Are you applying for Fiscal Sponsorship or Affiliation?

Fiscal Sponsorship

## 11. Is your project wanting to apply for the Comprehensive or the Grantor-Grantee fiscal sponsorship model?

Comprehensive.

### A. The publicly visible location of your governance document:

This is currently under Conda-Incubator project on GitHub.
https://github.com/conda-incubator/governance/blob/master/README.md
It will be moving out of the Conda-Incubator and into the Conda repo this summer. It will then be at https://github.com/conda/governance/blob/master/README.md

### B. The publicly visible location of your roadmap

https://github.com/orgs/conda/projects/2/views/1

### C. URL to “how to get started as a contributor” documentation:

The Conda Developer Guide is at https://conda.io/projects/conda/en/latest/dev-guide/index.html

### D. The names and email addresses of five people willing to act as signatories for your project:

**⇒⇒⇒⇒ We need 5 volunteers from the Steering Council here.**

1. Matthew R. Becker, becker.mr@gmail.com
2. John Kirkham, 
3. Marius van Niekerk, 
4. Jannis Leidel, jannis@leidel.info
5. Crystal Soja, 

And what are signatories?  They are the ones who sign the contract with NumFOCUS.  The most relevant bit of that contract is

> The Signatories, each a signatory hereto, hereby establish and comprise the initial members of the {{Leadership Body Name}} to carry out the Project's activities as stated in §3. The Signatories acknowledge that the {{Leadership Body Name}} shall be subject to all of the terms of this Agreement. As of the effective date of this Agreement, the Signatories hereby transfer all rights, benefits, obligations, and privileges under this Agreement to the {{Leadership Body Name}}.

Which to me says that the signatories are signing for the Steering Council, and the Steering Council is now responsible for what is in the document.

### E. The name of your project's leadership body:  It cannot contain the word "board" other than that it can be whatever you choose.

Conda Organization Steering Council

### F. A physical mailing address for your project

None.  Or someone's home address?

### G. Please provide a short description of your project geared toward funders/grantors/non-expert audience:  See example at the top of the page here: https://numfocus.org/project/pandas

Conda is widely used to simplify installation of open source software across operating systems, and to cleanly manage multiple (and possibly conflicting) run time environments on the same computer.

Or a one liner:

Conda simplifies dependency and environment management for open source software. 

### H. Please provide a short project description for developers/users:  See example under “Technical Details” tab at the bottom of this page: https://numfocus.org/project/pandas

Conda is an open source package management system and environment management system that runs on Windows, macOS, Linux and z/OS. Conda quickly installs, runs and updates packages and their dependencies. Conda easily creates, saves, loads and switches between environments on your local computer. Conda supports software written in any language.

### I. Please provide us with a a few sentences describing the known applications of your project:  See example under “Applications” tab at the bottom of this page: https://numfocus.org/project/pandas

Conda is an operating system, programming language, and domain agnostic tool. It is used in education, research and commercial applications to simplify software installation and manage run-time environments.

OK, that is not very specific, but it is true…

### J. Please provide us with project Industry, Languages, and Applications tags:

What Industries is your project mainly used in? Ex: Government, Higher Education, Finance, Business Applications, etc.
What Languages does your project use? Ex: Python, C, Javascript, R, Julia, etc.
What are some simple one or two-word applications for your project? Ex: Data Wrangling, Numeric Computing, Modeling, Visualization, etc.
See example here: https://numfocus.org/project/pandas

* Education, Government, Finance, Business, Artificial Intelligence, Science, Research 

### K. Any upcoming or annual events held by your project

Sprint at SciPy 2022, July 16-17, 2022 

### L. Link to your project's blog or newsletter:
We do not have one.  One will appear on conda.org later this year.

## 13. How does your project relate to or integrate with the existing ecosystem of NumFOCUS tools?

Many NumFOCUS tools have been packaged in Conda, and are widely deployed using Conda.  The most closely integrated project is conda-forge (https://numfocus.org/project/conda-forge).  Most of the NumFOCUS sponsored tools are available in conda, usually through conda-forge, including:

* NumPy
* Matplotlib
* pandas
* Project Jupyter
* IPython
* SciPy
* nteract
* Stan
* PyMC
* Julia
* PyTables
* Shogun
* SymPy
* FEniCS Project

And then we stopped looking.  Of the first 15 project listed on the NumFOCUS at least 14 of them have been made available through conda

## 14. Describe how your project furthers the NumFOCUS mission: https://numfocus.org/community/mission

The mission of NumFOCUS is to promote open practices in research, data, and scientific computing by serving as a fiscal sponsor for open source projects and organizing community-driven educational programs.

Conda enables tool developers to create versions of their tools that can be easily installed on many different operating systems. This lowers the barrier to using these tools and allows many users who otherwise could not manage installation of software dependencies, or multiple run-time environments. 

## 15. How many active contributors does your project currently have?

The Conda ecosystem consists of several projects. From June 2021 to May 2022 these projects had 5 or more contributors (commits only)

16 - grayskull
14 - conda-build
13 - conda 
13 - conda-docs
13 - conda-lock
  9 - constructor
  8 - governance
  7 - conda-package-handling
  6 - conda-pack

The number of unique committers across all projects is likely around 25 to 30.

## 16. Any comments you’d like to make on the number of your active contributors:

The number of committers is easy to measure, we believe this is a poor indicator of active contributors.  This does not include Pull Request reviews, call participation, training, code of conduct committee membership, and many other types of contribution.

## 17. What is your project doing to attract and/or mentor new contributors and maintainers?

We are holding a sprint at PyCon 2022. We also are planning to work with Outreachy for their upcoming intern cohort.

## 18. Where do you host conversations about project development and governance (e.g. mailing lists, forums, etc.), and how many participants do you have?

These are hosted in several places:

1. Issues in the conda and conda-organization GitHub repos
2. Slack, 100 people

We also have forums for users:

1. Google Group https://groups.google.com/a/anaconda.com/g/conda, 858 members
2. Gitter https://gitter.im/conda/home, 712 people

## 19. What license(s) does your project currently use?

We require a permissive license.  Licenses currently in use include

* BSD 3-Clause (most common)
* MIT (next most common)
* BSD
* CC-By-4.0
* CC0-1.0
* Apache-2.0

## 20. Projects must adopt the NumFOCUS Code of Conduct or one similar in spirit. Please tell us how you plan to meet this requirement:

Our Code of Conduct is currently in incubator status, and is based on the NumFOCUS template. We expect this to be fully deployed this summer.

## 21. Your Name (First & Last)

Dave Clements

## 22.Your Email

dclements@anaconda.com

**Comment by jaimergp** [comment]
I noticed one apostrophe vs semicolon typo: 

```diff
  9. Why do you want your project to join NumFOCUS?
  The Conda Organization currently has no legal status. We cannot accept funding or formally
- sponsor work or events, and we can;t manage trademarks. Joining NumFOCUS enables us to do all
+ sponsor work or events, and we can't manage trademarks. Joining NumFOCUS enables us to do all
  those things, and would also raise Conda's visibility in the open source scientific software
  community.
```

**Comment by tnabtaf** [comment]
Thanks @jaimergp, that's a common typo for me.  I will fix and update the PR

**Comment by jezdez** [comment]
As recorded in https://github.com/conda-incubator/governance/pull/51#issuecomment-1191316895 the vote on this fiscal sponsorship proposal has reached quorum and has passed.

**Comment by tnabtaf** [comment]
Unless people object, I am going to leave this issue open until we (hopefully) get fiscal sponsorship with NumFOCUS.

So far, they have acknowledge receipt of our application.
