### ISSUE TITLE
figure out attic vs conda-archive vs simply archiving projects in the conda org

### ISSUE THREAD

**Issue by beckermr** [conda-incubator/governance#56]
@jakirkham @jezdez We should settle on one thing. I don't think it matters what we do, but we need to be consistent.

**Comment by jezdez** [comment]
I think "archive" is a better, non-controversial term, while attic is culturally biased. Happy to open a PR to update the terminology in the governance policy.

**Comment by beckermr** [comment]
Sounds good to me! 

I think we want to archive projects in place and not use a separate org then?

**Comment by jezdez** [comment]
I would suggest using a separate org to prevent repo sprawl and make project statuses clear, basically showing the path a conda project can take over its lifecycle: incubation > maintenance > archive.

At least that was the reason I moved all those old repos into the conda-archive organization last year to clarify what is maintained, and what isn't. The lack of an active use of the governance policy made this possible, but I'm clear that we're past that now, so you're right we should have a clear way of doing that.
