### ISSUE TITLE
Set up "Communications" subteam

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/governance#81]
[Following the governance policy for subteams](https://github.com/conda-incubator/governance#sub-teams), as mentioned on the conda slack team, I'd like to initiate a communications subteam to better coordinate communication in the conda organizations. 

See the [formal proposal below](#issuecomment-1350893138).

As a first step, I'll propose to participate in the subteam as the required steering council member, but I'd like to invite other steering council members to join as well, if they are interested in this area of work.

Please respond below in case you're interested in joining the subteam.

**Comment by jezdez** [comment]
@conda-incubator/steering Please take a look at this proposal at your earlier convenience (I'll cross-post to slack as well).

@tnabtaf @ocefpaf @xhochy @jaimergp You have responded to my previous question on Slack, are you interested in joining the subteam?

**Comment by jaimergp** [comment]
Yes, please, I'd like to join!

**Comment by jezdez** [comment]
@conda-incubator/steering I only now realized this is a voting item in the governance policy. Here's my official proposal.

### Proposal

I hereby propose to form a new "Comms" subteam

### Role & Responsibility

The "Comms" subteam helps to improve the communication between the conda organization and the larger conda community and works in tandem with the steering council and projects under the conda governance policy.

The sub-team is responsible to help with communication efforts and help project maintainers and other conda organization members if/when they need help with communication topics (e.g. release announcements).

Some suggested fields of work (incomplete list):

- maintenance of Twitter, Mastodon and related social media presence
- co-administration and moderation of the [conda discourse](https://conda.discourse.group/) instance
- co-administration of mailing lists under the conda.org domain
- ...

### Members (ongoing list):

- @jezdez
- @jaimergp
- @tnabtaf
- ...

### Charter

[dynamic (self-organizing)](https://github.com/conda-incubator/governance/tree/0fa0e84f690e628fe7a232bb52938409b2fbc1e3#dynamic-charter)

---

### Vote

This proposal falls under the **["Sub-team Formation"](https://github.com/conda-incubator/governance/tree/0fa0e84f690e628fe7a232bb52938409b2fbc1e3#sub-team-formation)** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal. It **needs 50% of the Steering Council** to vote yea to pass.

To vote, please leave **"Yay"** or **"Nay"** below as comments.

If you would like to propose changes to the current proposal or have questions, please leave a comment below as well.

**This vote will end on 2022-12-21.**

**Comment by jaimergp** [comment]
Yay.

**Comment by mbargull** [comment]
Can we name this "communications" or the like?
When it comes to "official matters", general user documentation, etc. I'm inclined to step away from abbreviations and slang/cant to make things easily comprehensible for new/international users.

**Comment by jezdez** [comment]
@mbargull Good call out, I've updated the proposal to use "communications" instead.

**Comment by jezdez** [comment]
@beckermr I've added "website maintenance (conda.org)" to the proposal above. I don't think you meant the documentation websites, since they are related to the individual projects, right?

**Comment by ocefpaf** [comment]
> @tnabtaf @ocefpaf @xhochy @jaimergp You have responded to my previous question on Slack, are you interested in joining the subteam?

@jezdez while I'm willing to help this team with anything I can do I do not want to be a part of it. I'm afraid I don't have the time to be a "full time" member.

**Comment by mbargull** [comment]
> @mbargull Good call out, I've updated the proposal to use "communications" instead.

Thank you!

**Comment by mbargull** [comment]
Yay!

**Comment by chenghlee** [comment]
Yay!

**Comment by tnabtaf** [comment]
I would be happy to on (and even lead) this team.

**Comment by xhochy** [comment]
Copying from @ocefpaf:

@jezdez while I'm willing to help this team with anything I can do I do not want to be a part of it. I'm afraid I don't have the time to be a "full time" member.

**Comment by xhochy** [comment]
yay!

**Comment by ericdill** [comment]
Yay 🎉

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda-incubator/governance/blob/0fa0e84f690e628fe7a232bb52938409b2fbc1e3/steering.csv) there are 8 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (8 is at least 50% of 15).

It **has also passed** since it recorded 8 "yes" votes and 0 "no" votes giving 8/15 which is greater than 50% of 15.

It should be noted that the proposal was updated to use "communications" instead of "comms" as originally proposed.

**Comment by jezdez** [comment]
The repo and teams have been created at:

- https://github.com/conda/communications
- https://github.com/orgs/conda/teams/communications

@tnabtaf I've invited you to the team, I also added @jaimergp and me.

**Comment by beckermr** [comment]
FYI, vote passed with 100%. The vote percentage is computed with respect to those who voted. Otherwise, the quorum would default to 100% of the group.
