### ISSUE TITLE
Set up "Infrastructure" subteam

### ISSUE THREAD

**Issue by jezdez** [conda-incubator/governance#84]
@conda-incubator/steering Here's my official proposal to create a new conda infra team

### Proposal

I'm proposing to form a new "Infrastructure" subteam

### Team Charter

Following the governance policy, this is a [static](https://github.com/conda-incubator/governance/tree/963a16ee02126229ec57614b000e3480d8cea26d#static-charter) charter with the additional condition that any member of the steering council may join this team if they so choose without the approval of the rest of the steering council. 

The "Infrastructure" subteam helps with maintenance of the developer and community infrastructure of the conda project, as delegates of the conda steering council. 

That includes the conda, conda-archive and conda-incubator organizations on GitHub and related lower-level infrastructure systems that enable the steering council, projects under the conda governance policy and the larger conda community to participate in an effective, open and transparent Open Source ecosystem.

#### Work areas

- maintenance of GitHub repository settings and permissions
- responding to and coordinating of feedback in infrastructure-specific discussions in the [conda/infra](https://github.com/conda/infra) repo, e.g. coordination with other community stakeholders
- respond to project maintainer feedback about continuous integration systems and similar build systems
- password management of backend systems
- shared GitHub workflows and actions
- documentation system setup
- domain management (e.g. conda.org)
- maintenance of the existing repositories:
  - https://github.com/conda/.github
  - https://github.com/conda/actions
  - https://github.com/conda/infra

#### Scope

The "Infrastructure" team works as delegates of the conda steering council and follows the Conda Code of Conduct. It provides the necessary help to members of the conda ecosystem, when they request it, and limits its scope of work according to their roles and responsibilities mentioned above.

#### Proposed members:

- @jezdez
- @kenodegard
- @dbast 
- @beckermr 

EDIT: Changed from "dynamic" to "static" charter, meaning:
EDIT 2: fleshed out team charter
EDIT 3: added actions and .github repos

---

### Vote

This proposal falls under the **["Sub-team Formation"](https://github.com/conda-incubator/governance/tree/963a16ee02126229ec57614b000e3480d8cea26d#sub-team-formation)** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal. It **needs 50% of the Steering Council** to vote yea to pass.

To vote, please leave **"Yes"** or **"No"** below as comments.

If you would like to propose changes to the current proposal or have questions, please leave a comment below as well.

**This vote will end on 2022-02-01.**

**Comment by mariusvniekerk** [comment]
Yes

**Comment by marcelotrevisani** [comment]
Yes 👍

**Comment by ocefpaf** [comment]
Yes

**Comment by beckermr** [comment]
I made two changes

- I added a clause that any member of the steering committee may join this team if they desire without approval of the steering council. 

- I added myself to listed set of members. 

Yes.

**Comment by mbargull** [comment]
Yes

**Comment by chenghlee** [comment]
Yes

**Comment by xhochy** [comment]
yes

**Comment by jezdez** [comment]
Yes

**Comment by jakirkham** [comment]
Yes

**Comment by jezdez** [comment]
## Voting Results

This was a standard, non-timed-out vote.

Among [Steering Council members](https://github.com/conda-incubator/governance/blob/a2059652e1d41ecf3921c69b3ca4f058abde0b2a/steering.csv) there are 10 "yes", 0 "no", and no abstentions.

This vote **has reached quorum** (10 is at least 50% of 15).

It **has also passed** since it recorded 10 "yes" votes and 0 "no" votes giving 10/10 which is greater than 50% of 10.

**Comment by jezdez** [comment]
I've created the team and invited everyone listed above: https://github.com/orgs/conda/teams/infrastructure

For consistency, I've also renamed the conda/infra repository to conda/infrastructure.

**Comment by dbast** [comment]
Thanks everybody. Happy to be part of the infrastructure team!
